language: java
services:
- mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS food;'
test:
  adapter: mysql2
  database: food
  username: food
  password: food
jdk:
- oraclejdk8
sudo: required
dist: trusty